Fix admin nome
Ru4nGR/sisdle_web pull request #18
Opened 2021-07-15 23:45 UTC by Angelo-Netho

2021-07-15 23:48 UTC, Ru4nGR reviewed
Qual o sentido do Admin ter o nome em letras minúsculas?

2021-07-15 23:50 UTC, Angelo-Netho commented
> Qual o sentido do Admin ter o nome em letras minúsculas?

Para padronizar no banco de dados e não permitir X variações diferentes com um nome de X letras

Exemplo:
Ruan
ruan
RUan
...

2021-07-15 23:56 UTC, Ru4nGR requested changes
Faz sentido existirem múltiplos Admins com o mesmo nome mas com capitalização diferente. Mas faz sentido filtrar para evitar alguns conflitos mais chatos. Mas a ideia é usar o nome do Admin em algumas partes da aplicação, principalmente para gerar a descrição da lixeira proceduralmente, logo, é necessário preservar a capitalização do nome do Admin.

Um jeito melhor de implementar essa checagem é guardando o nome do Admin como é, e então checando Admins com o mesmo nome, ambos os operandos com a mesma capitalização (toLower() / toUpper()).

2021-07-16 01:26 UTC, Ru4nGR approved these changes
Muito bom.

2021-07-16 01:26 UTC, merged