Fix organiza rotas
Ru4nGR/sisdle_web pull request #2
Opened 2021-05-18 22:32 UTC by Angelo-Netho

Os controllers foram separados cada um em seu respectivo arquivo, o servidor.ts foi atualizado para aplicar as mudanças e o antigo controller foi removido

2021-05-22 17:51 UTC, Ru4nGR commented
Dei merge da master nessa branch para resolver conflitos.

2021-05-22 17:55 UTC, Ru4nGR requested changes
Muito bom, gostaria de pedir duas coisas antes de dar merge:

- Mude o nome dos controller para seguir o padrão: controllers/lixeira => controllers/LixeiraController, etc.
- Exporte apenas o router do controller, e ponha app.user('/{controller}', {controller}) diretamente no arquivo do servidor; eu entendi a sua ideia e achei muito boa, mas eu acho melhor deixar mais explicito.

Apenas faça essas mudanças usando essa branch mesmo, depois de push que as mudanças são registradas nessa PR, então eu darei merge.

2021-05-24 15:48 UTC, Angelo-Netho commented
Feito as mudanças requisitadas.

2021-05-24 17:02 UTC, Ru4nGR approved these changes
Isso ai.

2021-05-24 17:03 UTC, merged